apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kong-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: kong
  source:
    repoURL: https://charts.konghq.com
    chart: kong-operator
    targetRevision: 1.0.2
    helm:
      values: |
        image:
          tag: 2.0.5
        env:
          enable_controller_konnect: true
          enable_controller_gateway: true
          enable_controller_controlplane: true
          enable_controller_dataplane: true
          enable_controller_konglicense: true
        global:
          webhooks:
            options:
              certManager:
                enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kong-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
