name: Sync decK config(Konbot)

on:
  push:
    paths:
      - deck/global/*.yaml
      - deck/konbot/*.yaml
      - .github/workflows/sync-konbot.yaml
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6
      - name: Setup deck
        uses: kong/setup-deck@v1
        with:
          deck-version: 1.49.0
      - name: Add tag
        run: |
          deck file add-tags konbot \
            -s deck/konbot/kong.yaml
      - name: Diff current environment
        run: |
          deck gateway diff \
            deck/konbot/kong.yaml \
            --select-tag konbot \
            --konnect-token ${{ secrets.KONNECT_TOKEN }}
      - name: Sync gateway config
        run: |
          deck gateway sync \
            deck/konbot/kong.yaml \
            --select-tag konbot \
            --konnect-token ${{ secrets.KONNECT_TOKEN }}
